import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
export const metadata = {
  title: "shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
          <AntdRegistry >
            {children}
          </AntdRegistry>
      </body>
    </html>
  );
}
